/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MySQLManager;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;
import modelo.Autor;
import modelo.Boleta;

import modelo.Cliente;
import modelo.Libro;
import modelo.Trabajador;

/**
 *
 * @author MegaJoc
 */
public class ventaClientes extends javax.swing.JFrame {

    ArrayList<Libro> listaLibro = new ArrayList<>();
    ArrayList<Libro> listaLibroBoleta = new ArrayList<>();
    ArrayList<Cliente> listaCliente = new ArrayList<>();
    ArrayList<Autor> listaAutor = new ArrayList<Autor>();
    ArrayList<Trabajador> listaTrabajador = new ArrayList<>();
    ArrayList<Boleta> listaBoleta = new ArrayList<Boleta>();
    int ultimaboleta = 0;
    Cliente cliente = new Cliente();
    Trabajador trabajador = new Trabajador();
    Libro libro = new Libro();

    /**
     * Creates new form ventaClientes
     */
    public ventaClientes() {
       
        initComponents();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idClienteVentaTXT = new javax.swing.JTextField();
        idLibroVentaTXT = new javax.swing.JTextField();
        idTrabajadorVentaTXT = new javax.swing.JTextField();
        agregarIdClienteBTN = new javax.swing.JButton();
        agregarIdLibroBTN = new javax.swing.JButton();
        agregarIdTrabajadorBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        boletaTBL = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        comprarBTN = new javax.swing.JButton();
        verBoletasBTN = new javax.swing.JButton();
        idclienteLBL = new javax.swing.JLabel();
        idlibroLBL = new javax.swing.JLabel();
        idtrabajadorLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Página de venta de libros a clientes Fast Development");

        jLabel2.setText("Ingrese ID de libro a comprar.");

        jLabel3.setText("Ingrese su ID de cliente.");

        jLabel4.setText("Ingrese su ID de trabajador.");

        idClienteVentaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idClienteVentaTXTKeyTyped(evt);
            }
        });

        idLibroVentaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idLibroVentaTXTKeyTyped(evt);
            }
        });

        idTrabajadorVentaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTrabajadorVentaTXTKeyTyped(evt);
            }
        });

        agregarIdClienteBTN.setText("Agregar");
        agregarIdClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdClienteBTNActionPerformed(evt);
            }
        });

        agregarIdLibroBTN.setText("Agregar");
        agregarIdLibroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdLibroBTNActionPerformed(evt);
            }
        });

        agregarIdTrabajadorBTN.setText("Agregar");
        agregarIdTrabajadorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdTrabajadorBTNActionPerformed(evt);
            }
        });

        boletaTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre de libro", "Precio neto", "Precio con IVA", "Costo IVA", "Fecha de venta", "Hora de venta", "Nombre de cliente", "Nombre de trabajador"
            }
        ));
        jScrollPane2.setViewportView(boletaTBL);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Vista previa de su boleta, si los datos son correctos, presione el botón \"Comprar\" para ver la forma de pago.");

        comprarBTN.setText("Comprar");

        verBoletasBTN.setText("Ver boletas");

        idclienteLBL.setText("Ingrese Id de cliente");

        idlibroLBL.setText("Ingrese Id de libro");

        idtrabajadorLBL.setText("Ingrese Id de trabajador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLibroVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idTrabajadorVentaTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(agregarIdTrabajadorBTN)
                                        .addGap(18, 18, 18)
                                        .addComponent(idtrabajadorLBL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(agregarIdLibroBTN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idlibroLBL))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(339, 339, 339)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comprarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verBoletasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idClienteVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(agregarIdClienteBTN)
                        .addGap(18, 18, 18)
                        .addComponent(idclienteLBL))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idClienteVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarIdClienteBTN)
                    .addComponent(idclienteLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comprarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLibroVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarIdLibroBTN)
                    .addComponent(idlibroLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(verBoletasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTrabajadorVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarIdTrabajadorBTN)
                    .addComponent(idtrabajadorLBL))
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idClienteVentaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClienteVentaTXTKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idClienteVentaTXTKeyTyped

    private void idLibroVentaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idLibroVentaTXTKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idLibroVentaTXTKeyTyped

    private void idTrabajadorVentaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTrabajadorVentaTXTKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idTrabajadorVentaTXTKeyTyped

    private void agregarIdClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdClienteBTNActionPerformed
       
        MySQLManager manager = new MySQLManager("localhost", "3306", "bibliotecafastdevelopment", "root", "");
        manager.executeQueryConsultaLLenaTablaClientes(listaCliente);
        

        int idCliente;
        idCliente = Integer.parseInt(idClienteVentaTXT.getText());

        for (int i = 0; i < listaCliente.size(); i++) {
            if (idCliente == listaCliente.get(i).getId_cliente()) {
                cliente = listaCliente.get(i);
                System.out.println(cliente.getId_cliente());
                idclienteLBL.setText("Id de cliente actual en boleta" + cliente.getId_cliente());
            } else {
                idclienteLBL.setText("Cliente no existe en la Base de datos");
            }
            
        }

        mostrarTabla();
    }//GEN-LAST:event_agregarIdClienteBTNActionPerformed
    private void limpiarTabla() {
        for (int i = 0; i < listaCliente.size(); i++) {
            listaCliente.remove(i);
        }
    }

    private void mostrarTabla() {
        MySQLManager manager = new MySQLManager("localhost", "3306", "bibliotecafastdevelopment", "root", "");
        manager.executeQueryConsultaLLenaTablaLibro(listaLibro);
        manager.executeQueryConsultaLLenaTablaClientes(listaCliente);
        manager.executeQueryConsultaLLenaTablaTrabajadores(listaTrabajador);

        
        String columnas[]={"Nombre libro","Precio Neto", "Precio con Iva","Costo IVA","Fecha Venta","Nombre Cliente","Nombre Trabajador"};
        String matriz[][] = new String[listaLibroBoleta.size()][4];
       
        if (listaLibro.isEmpty()) {
            String[] columna = {"No hay libros en ", "la base de datos"};
            String[][] matrix = new String[1][1];
            DefaultTableModel dt = new DefaultTableModel(matrix, columna);
            boletaTBL.setModel(dt);

        } else {
        for (int i = 0; i < listaLibroBoleta.size(); i++) {



            String idCliente = Integer.toString(listaCliente.get(i).getId_cliente());
            String precio_ref = Integer.toString(listaLibroBoleta.get(i).getPrecio_ref());
            String precio_iva = precio_ref + Double.toString(listaLibroBoleta.get(i).getPrecio_ref() * 0.19);
         
            matriz[i][0] = idCliente;
            matriz[i][1] = Integer.toString(listaLibroBoleta.get(i).getPrecio_ref());
            matriz[i][2] = precio_iva;
            matriz[i][3] = precio_ref + Double.toString(listaLibroBoleta.get(i).getPrecio_ref() * 0.19);
            
            matriz[i][4] ="";
            matriz[i][5] ="";
            matriz[i][6] ="";
            


            
        }
        DefaultTableModel dtm = new DefaultTableModel(matriz, columnas);
        boletaTBL.setModel(dtm); 

    }
    }
    private void agregarIdLibroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdLibroBTNActionPerformed
        // TODO add your handling code here:  
        MySQLManager manager = new MySQLManager("localhost", "3306", "bibliotecafastdevelopment", "root", "");        
        manager.executeQueryConsultaLLenaTablaLibro(listaLibro);          
        int idLibro;
        
        idLibro = Integer.parseInt(idLibroVentaTXT.getText());
        
        for (int i = 0; i < listaLibro.size(); i++) {
            System.out.println(listaLibro.get(i).getId_libro());
            if (idLibro == listaLibro.get(i).getId_libro()) {
                libro = listaLibro.get(i);
                idlibroLBL.setText("Id de Libro actual en boleta" + libro.getId_libro());
            } else {
                idlibroLBL.setText("Libro no existe en la Base de datos");
            }

        }
        mostrarTabla();
    }//GEN-LAST:event_agregarIdLibroBTNActionPerformed

    private void agregarIdTrabajadorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdTrabajadorBTNActionPerformed
        MySQLManager manager = new MySQLManager("localhost", "3306", "bibliotecafastdevelopment", "root", "");
        manager.executeQueryConsultaLLenaTablaTrabajadores(listaTrabajador);

        int idtrabajador;
        idtrabajador = Integer.parseInt(idTrabajadorVentaTXT.getText());

        for (int i = 0; i < listaTrabajador.size(); i++) {
            if (idtrabajador == listaTrabajador.get(i).getId_trabajador()) {
                trabajador = listaTrabajador.get(i);
                idlibroLBL.setText("Id de Trabajador actual en boleta" + trabajador.getId_trabajador());
            } else {
                System.out.println("Trabajador no existe en la Base de datos");
            }

        }
        mostrarTabla();
    }//GEN-LAST:event_agregarIdTrabajadorBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarIdClienteBTN;
    private javax.swing.JButton agregarIdLibroBTN;
    private javax.swing.JButton agregarIdTrabajadorBTN;
    private javax.swing.JTable boletaTBL;
    private javax.swing.JButton comprarBTN;
    private javax.swing.JTextField idClienteVentaTXT;
    private javax.swing.JTextField idLibroVentaTXT;
    private javax.swing.JTextField idTrabajadorVentaTXT;
    private javax.swing.JLabel idclienteLBL;
    private javax.swing.JLabel idlibroLBL;
    private javax.swing.JLabel idtrabajadorLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton verBoletasBTN;
    // End of variables declaration//GEN-END:variables

}
