/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MySQLManager;
import java.util.ArrayList;
import modelo.Cliente;
import modelo.Libro;
import modelo.Trabajador;

/**
 *
 * @author MegaJoc
 */
public class ventaClientes extends javax.swing.JFrame {

    ArrayList<Libro> listaLibro = new ArrayList<>();
    ArrayList<Cliente> listaCliente = new ArrayList<>();
    ArrayList<Trabajador> listaTrabajador = new ArrayList<>();
    ArrayList<Libro> listaLibroFactura = new ArrayList<>();

    /**
     * Creates new form ventaClientes
     */
    public ventaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agregarNuevoClienteBTN = new javax.swing.JButton();
        agregarTrabajadorBTN = new javax.swing.JButton();
        verLibrosBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idClienteVentaTXT = new javax.swing.JTextField();
        idLibroVentaTXT = new javax.swing.JTextField();
        idTrabajadorVentaTXT = new javax.swing.JTextField();
        agregarIdClienteBTN = new javax.swing.JButton();
        agregarIdLibroBTN = new javax.swing.JButton();
        agregarIdTrabajadorBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vistaPreviaCompraTBL = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        agregarABoletaBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        comprarBTN = new javax.swing.JButton();
        verBoletasBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Página de venta de libros a clientes Fast Development");

        agregarNuevoClienteBTN.setText("Agregar nuevo cliente");
        agregarNuevoClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNuevoClienteBTNActionPerformed(evt);
            }
        });

        agregarTrabajadorBTN.setText("Agregar nuevo trabajador");
        agregarTrabajadorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTrabajadorBTNActionPerformed(evt);
            }
        });

        verLibrosBTN.setText("Ver libros");

        jLabel2.setText("Ingrese ID de libro a comprar.");

        jLabel3.setText("Ingrese su ID de cliente.");

        jLabel4.setText("Ingrese su ID de trabajador.");

        idClienteVentaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idClienteVentaTXTKeyTyped(evt);
            }
        });

        idLibroVentaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idLibroVentaTXTKeyTyped(evt);
            }
        });

        idTrabajadorVentaTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTrabajadorVentaTXTKeyTyped(evt);
            }
        });

        agregarIdClienteBTN.setText("Agregar");
        agregarIdClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdClienteBTNActionPerformed(evt);
            }
        });

        agregarIdLibroBTN.setText("Agregar");
        agregarIdLibroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdLibroBTNActionPerformed(evt);
            }
        });

        agregarIdTrabajadorBTN.setText("Agregar");
        agregarIdTrabajadorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIdTrabajadorBTNActionPerformed(evt);
            }
        });

        vistaPreviaCompraTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre de cliente", "Nombre de libro", "Precio de libro", "Nombre de trabajador"
            }
        ));
        jScrollPane1.setViewportView(vistaPreviaCompraTBL);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Revise sus datos en esta tabla antes de confirmar:");

        agregarABoletaBTN.setText("Agregar a la boleta");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre de libro", "Precio neto", "Precio con IVA", "Costo IVA", "Fecha de venta", "Hora de venta", "Nombre de cliente", "Nombre de trabajador"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Vista previa de su boleta, si los datos son correctos, presione el botón \"Comprar\" para ver la forma de pago.");

        comprarBTN.setText("Comprar");

        verBoletasBTN.setText("Ver boletas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comprarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verBoletasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verLibrosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarNuevoClienteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarTrabajadorBTN)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(idLibroVentaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                            .addComponent(idClienteVentaTXT))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agregarIdLibroBTN)
                                            .addComponent(agregarIdClienteBTN)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idTrabajadorVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(agregarIdTrabajadorBTN)))
                                .addGap(55, 55, 55)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(30, 30, 30)))
                        .addComponent(agregarABoletaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idClienteVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarIdClienteBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarNuevoClienteBTN)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idLibroVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarIdLibroBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verLibrosBTN)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idTrabajadorVentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarIdTrabajadorBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarTrabajadorBTN)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarABoletaBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comprarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verBoletasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarNuevoClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNuevoClienteBTNActionPerformed
        new vistaClientes().setVisible(true);
    }//GEN-LAST:event_agregarNuevoClienteBTNActionPerformed

    private void agregarTrabajadorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTrabajadorBTNActionPerformed
        new vistaTrabajadores().setVisible(true);
    }//GEN-LAST:event_agregarTrabajadorBTNActionPerformed

    private void idClienteVentaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClienteVentaTXTKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idClienteVentaTXTKeyTyped

    private void idLibroVentaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idLibroVentaTXTKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idLibroVentaTXTKeyTyped

    private void idTrabajadorVentaTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTrabajadorVentaTXTKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idTrabajadorVentaTXTKeyTyped

    private void agregarIdClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdClienteBTNActionPerformed
        int idCliente;
        idCliente = Integer.parseInt(idClienteVentaTXT.getText());

        Cliente cliente = new Cliente();
        cliente.getId_cliente();

        limpiarTabla();
        mostrarTabla();
    }//GEN-LAST:event_agregarIdClienteBTNActionPerformed
    private void limpiarTabla() {
        for (int i = 0; i < listaCliente.size(); i++) {
            listaCliente.remove(i);
        }
    }

    private void mostrarTabla() {
        limpiarTabla();
        MySQLManager manager = new MySQLManager("localhost", "3307", "bibliotecafastdevelopment", "root", "");
        manager.executeQueryConsultaLLenaTablaLibro(listaLibro);
        manager.executeQueryConsultaLLenaTablaClientes(listaCliente);
        manager.executeQueryConsultaLLenaTablaTrabajadores(listaTrabajador);

        String matriz[][] = new String[listaCliente.size()][4];

        for (int i = 0; i < listaCliente.size(); i++) {

            String idCliente = Integer.toString(listaCliente.get(i).getId_cliente());

            String precio_ref = Integer.toString(listaLibroFactura.get(i).getPrecio_ref());
            String precio_iva = precio_ref + Double.toString(listaLibroFactura.get(i).getPrecio_ref() * 0.19);

            matriz[i][0] = listaCliente.get(i).getNombre();
            matriz[i][1] = Integer.toString(listaLibroFactura.get(i).getPrecio_ref());
            matriz[i][2] = Double.toString(listaLibroFactura.get(i).getPrecio_ref() * 0.19);
            matriz[i][3] = precio_ref + Double.toString(listaLibroFactura.get(i).getPrecio_ref() * 0.19);

        }

    }
    private void agregarIdLibroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdLibroBTNActionPerformed
        // TODO add your handling code here:
        int idLibro;
        idLibro = Integer.parseInt(idLibroVentaTXT.getText());
      
        Trabajador t1 = new Trabajador();
        
        t1.getId_trabajador();
                 
        limpiarTabla();
        mostrarTabla();
    }//GEN-LAST:event_agregarIdLibroBTNActionPerformed

    private void agregarIdTrabajadorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIdTrabajadorBTNActionPerformed
        // TODO add your handling code here:
        
        int idTrabajador;
        idTrabajador = Integer.parseInt(idTrabajadorVentaTXT.getText());
      
        Trabajador t1 = new Trabajador();
        
        t1.getId_trabajador();
                 
        limpiarTabla();
        mostrarTabla();
    }//GEN-LAST:event_agregarIdTrabajadorBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarABoletaBTN;
    private javax.swing.JButton agregarIdClienteBTN;
    private javax.swing.JButton agregarIdLibroBTN;
    private javax.swing.JButton agregarIdTrabajadorBTN;
    private javax.swing.JButton agregarNuevoClienteBTN;
    private javax.swing.JButton agregarTrabajadorBTN;
    private javax.swing.JButton comprarBTN;
    private javax.swing.JTextField idClienteVentaTXT;
    private javax.swing.JTextField idLibroVentaTXT;
    private javax.swing.JTextField idTrabajadorVentaTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton verBoletasBTN;
    private javax.swing.JButton verLibrosBTN;
    private javax.swing.JTable vistaPreviaCompraTBL;
    // End of variables declaration//GEN-END:variables

}
